KompiuteriuSurinkimoSistema-master/KompiuteriuSurinkimoSistema-master/KompiuteriuSurinkimoSistema/Controllers/PartController.cs
using ComputerBuildSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.IO;
using System.Text.RegularExpressions;
using System.Text.Json;
using HtmlAgilityPack;
using System.Net.Http;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;
using Mysqlx.Session;

namespace ComputerBuildSystem.Controllers
{
    public class PartController : Controller
    {

        private readonly PsaContext _context; // Database context
        private readonly BenchmarkAPI _benchmarkAPI; // Benchmark API

        /// <summary>
        /// Constructor
        /// </summary>
        public PartController(PsaContext context, BenchmarkAPI benchmarkAPI)
        {
            _context = context;
            _benchmarkAPI = benchmarkAPI;
        }

        public IActionResult OpenPartList()
        {
            var parts = _context.ComputerParts.ToList(); // Get all parts from the database

            var sessionIds = HttpContext.Session.GetString("GPUcompare"); // Get the ids of the parts that are being compared
            List<int> buildIds = sessionIds != null ? sessionIds.Split(',').Select(int.Parse).ToList() : new List<int>(); // Convert the string to a list of integers

            List<ComputerPart> compareGPU = parts.Where(p => buildIds.Contains(p.Id)).ToList(); // Get the parts that are being compared

            HttpContext.Session.SetString("CompareGPU", JsonSerializer.Serialize(compareGPU)); // Save the parts that are being compared to the session

            ViewBag.CompareGPU = compareGPU; // Send the parts that are being compared to the view
            return View("PartList", parts);
        }

        public IActionResult Filter(string type, List<ComputerPart> parts)
        {
            if (string.IsNullOrEmpty(type))
            {
                parts = _context.ComputerParts.ToList(); // Get base part
            }
            else
            {
                parts = _context.ComputerParts.Where(p => p.Type == type).ToList(); // Get specific part with type
            }

            return View("PartList", parts);
        }


        public IActionResult OpenAddPart()
        {
            return View("AddPart");
        }

        // POST: Handle the form submission
        [HttpPost]
        public IActionResult AddPart(IFormCollection form)
        {

            if (!ValidatePartData(form)) // Validate the form data
            {
                ModelState.AddModelError("ErrorMessage", "No empty fields allowed."); // Add an error message
                return View(form);
            }

            var type = form["Type"]; // Get the type of the part
            var newPart = new ComputerPart // Create a new part
            {
                Name = form["Name"],
                Manufacturer = form["Manufacturer"],
                Model = form["Model"],
                Type = type,
                Price = double.Parse(form["Price"]),
                Quantity = int.Parse(form["Quantity"]),
                Description = form["Description"]
            };

            _context.ComputerParts.Add(newPart); // Add the part to the database

            switch (type) // Add the part to the correct table based on the type
            {
                case "GPU":
                    var gpu = new Gpu
                    {
                        Memory = int.Parse(form["Memory"]),
                        MemoryType = form["MemoryType"],
                        MemoryFrequency = int.Parse(form["Frequency"]),
                        Connection = form["Connection"],
                        RamQuantity = int.Parse(form["RamQuantity"]),
                        RamType = form["RamType"],
                        Power = int.Parse(form["Power"]),
                        Dimensions = form["Dimensions"],
                        IdNavigation = newPart
                    };
                    _context.Gpus.Add(gpu);
                    break;
                case "CPU":
                    var cpu = new Cpu
                    {
                        Memory = form["Memory"],
                        Connection = form["Connection"],
                        Cores = int.Parse(form["Cores"]),
                        Frequency = int.Parse(form["Frequency"]),
                        Power = int.Parse(form["Power"]),
                        IdNavigation = newPart
                    };
                    _context.Cpus.Add(cpu);
                    break;
                case "RAM":
                    var ram = new Ram
                    {
                        Type = form["RamType"],
                        Frequency = int.Parse(form["Frequency"]),
                        Voltage = int.Parse(form["Voltage"]),
                        Amount = int.Parse(form["Amount"]),
                        IdNavigation = newPart
                    };
                    _context.Rams.Add(ram);
                    break;
                case "Case":
                    var computerCase = new Case
                    {
                        Standarts = form["Standard"],
                        Dimensions = form["Dimensions"],
                        Color = form["Color"],
                        IdNavigation = newPart
                    };
                    _context.Cases.Add(computerCase);
                    break;
                case "PSU":
                    var psu = new Psu
                    {
                        Power = int.Parse(form["Power"]),
                        SizeStandart = form["Size"],
                        IdNavigation = newPart
                    };
                    _context.Psus.Add(psu);
                    break;
                case "Motherboard":
                    var motherboard = new Motherboard
                    {
                        MaximumMemoryFrequency = int.Parse(form["MaxFrequency"]),
                        MemoryStandart = form["RamStandard"],
                        MaximumAmountOfMemory = int.Parse(form["MaxMemory"]),
                        CpuSocket = form["CpuSocket"],
                        GpuSocket = form["GpuSocket"],
                        MemoryConnection = form["MemoryConnection"],
                        SizeStandart = form["SizeStandard"],
                        IdNavigation = newPart
                    };
                    _context.Motherboards.Add(motherboard);
                    break;
                case "Hard disk":
                    var hdd = new HardDisk
                    {
                        Type = form["DiskType"],
                        Capacity = form["Capacity"],
                        ReadingSpeed = int.Parse(form["ReadingSpeed"]),
                        WritingSpeed = int.Parse(form["WritingSpeed"]),
                        Connection = form["Connection"],
                        IdNavigation = newPart
                    };
                    _context.HardDisks.Add(hdd);
                    break;
            }

            _context.SaveChanges(); // Save the changes to the database
            return RedirectToAction("OpenPartList");
        }

        /// <summary>
        /// Validate the form data
        /// </summary>
        /// <param name="form">Form to valide part of</param>
        /// <returns>True if valid, false otherwise</returns>
        public static bool ValidatePartData(IFormCollection form)
        {
            foreach (var key in form.Keys)
            {
                if (form[key] == "") // Check if any of the fields are empty
                    return false;
            }

            return true;
        }

        public IActionResult OpenPartInfo(int id)
        {
            var part = _context.ComputerParts
                .Include(p => p.Cpu)
                .Include(p => p.Gpu)
                .Include(p => p.Ram)
                .Include(p => p.Motherboard)
                .Include(p => p.Psu)
                .Include(p => p.Case)
                .Include(p => p.HardDisk)
                .FirstOrDefault(x => x.Id == id); // Get the part with all part types from the database

            return View("PartInfo", part);
        }

        public IActionResult DeletePart(int id)
        {
            var part = _context.ComputerParts.Find(id); // Find the part in the database
            if (part == null)
            {
                return NotFound(); // Return not found if the part is not found
            }

            return Json(new { confirm = true, message = "Are you sure you want to delete this part?" }); // Return a confirmation message
        }

        public IActionResult Delete(int id)
        {
            _context.ComputerParts.Where(p => p.Id == id).ExecuteDelete(); // Delete the part from the database

            _context.SaveChanges();

            return RedirectToAction("OpenPartList");
        }

        public IActionResult OpenEditPart(int id)
        {
            var part = _context.ComputerParts
                .Include(p => p.Cpu)
                .Include(p => p.Gpu)
                .Include(p => p.Ram)
                .Include(p => p.Motherboard)
                .Include(p => p.Psu)
                .Include(p => p.Case)
                .Include(p => p.HardDisk)
                .FirstOrDefault(m => m.Id == id); // Get the part with all part types from the database


            return View("EditPart", part);
        }

        [HttpPost]
        public IActionResult EditPart(ComputerPart part, IFormCollection form)
        {
            if (!ValidatePartData(form)) // Validate the form data
            {
                ModelState.AddModelError("ErrorMessage", "No empty fields allowed."); // Add an error message
                return View(part);
            }

            _context.Update(part); // Update the part in the database
            _context.SaveChanges();

            return RedirectToAction("OpenPartList"); // Redirect to the part list

KompiuteriuSurinkimoSistema-master/KompiuteriuSurinkimoSistema-master/KompiuteriuSurinkimoSistema/Views/Part/AddPart.cshtml
@{
    ViewData["Title"] = "Add New Part";
}

<h2>@ViewData["Title"]</h2>

@if (ViewData.ModelState.ContainsKey("ErrorMessage"))
{
    <div class="alert alert-danger">
        @foreach (var error in ViewData.ModelState["ErrorMessage"].Errors)
        {
            <p>@error.ErrorMessage</p>
        }
    </div>
}


<form asp-action="AddPart" method="post" id="partForm">
    <div class="form-group">
        <label for="type">Type of Part:</label>
        <select id="partType" name="Type" class="form-control" onchange="updateFormFields()">
            <option value="">Select Type</option>
            <option value="Case">Case</option>
            <option value="PSU">PSU</option>
            <option value="Hard disk">Hard Disk</option>
            <option value="GPU">GPU</option>
            <option value="CPU">CPU</option>
            <option value="RAM">RAM</option>
            <option value="Motherboard">Motherboard</option>
        </select>
    </div>

    <div class="form-group">
        <label for="Name">Name</label>
        <input type="text" name="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Manufacturer">Manufacturer</label>
        <input type="text" name="Manufacturer" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Model">Model</label>
        <input type="text" name="Model" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Price">Price</label>
        <input type="number" name="Price" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Quantity">Quantity</label>
        <input type="number" name="Quantity" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Description">Description</label>
        <textarea name="Description" class="form-control" ></textarea>
    </div>

    <div id="dynamicFields"></div>

    <button type="submit" class="btn btn-success" style="margin: 5px;">Add Part</button>
</form>

@section Scripts {
    <script>
        function updateFormFields() {
            const type = document.getElementById("partType").value;
            const fieldsContainer = document.getElementById("dynamicFields");

            fieldsContainer.innerHTML = '';

            if (type === "CPU") {
                        fieldsContainer.innerHTML += 
                `<div class="form-group">
                    <label for="Memory">Memory:</label>
                    <input type="text" name="Memory" class="form-control" />
                </div>
                 <div class="form-group">
                    <label for="Connection">Connection:</label>
                    <input type="text" name="Connection" class="form-control" />
                </div>
                 <div class="form-group">
                    <label for="Cores">Cores:</label>
                    <input type="number" name="Cores" class="form-control" />
                </div>

                <div class="form-group">
                    <label for="Frequency">Frequency:</label>
                    <input type="number" name="Frequency" class="form-control" />
                </div>
                <div class="form-group">
                    <label for="Power">Power:</label>
                    <input type="number" name="Power" class="form-control" />
                </div>`
                ;
            }

            if (type === "GPU") {
                fieldsContainer.innerHTML += 
                    `<div class="form-group">
                        <label for="Memory">Memory:</label>
                        <input type="number" name="Memory" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="MemoryType">Memory type:</label>
                        <input type="text" name="MemoryType" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="Frequency">Memory frequency:</label>
                        <input type="number" name="Frequency" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="Connection">Connection:</label>
                        <input type="text" name="Connection" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="RamQuantity">RAM Quantity:</label>
                        <input type="number" name="RamQuantity" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="RamType">RAM Type:</label>
                        <input type="text" name="RamType" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="Power">Power:</label>
                        <input type="number" name="Power" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="Dimensions">Dimensions:</label>
                        <input type="text" name="Dimensions" class="form-control" />
                    </div>
                    `;
            }

            if (type === "RAM") {
                fieldsContainer.innerHTML += 
                    `<div class="form-group">
                        <label for="Type">Type:</label>
                        <input type="text" name="Type" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="Frequency">Frequency:</label>
                        <input type="number" name="Frequency" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="Voltage">Voltage:</label>
                        <input type="number" name="Voltage" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="Amount">Amount:</label>
                        <input type="number" name="Amount" class="form-control" />
                    </div>
                    `;
            }

            if (type === "Case") {
                fieldsContainer.innerHTML += 
                    `<div class="form-group">
                        <label for="Standard">Size standard:</label>
                        <input type="text" name="Standard" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="Dimensions">Dimensions:</label>
                        <input type="text" name="Dimensions" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="Color">Color:</label>
                        <input type="text" name="Color" class="form-control" />
                    </div>
                    `;
            }

            if (type === "PSU") {
                fieldsContainer.innerHTML += 
                    `<div class="form-group">
                        <label for="Power">Power:</label>
                        <input type="number" name="Power" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="Size">Size standard:</label>
                        <input type="text" name="Size" class="form-control" />
                    </div>`;
            }

            if (type === "Motherboard") {
                fieldsContainer.innerHTML += 
                    `<div class="form-group">
                        <label for="MaxFrequency">Maximum memory frequency:</label>
                        <input type="number" name="MaxFrequency" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="RamStandard">Ram standard:</label>
                                <input type="text" name="RamStandard" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="MaxMemory">Maximum memory amount:</label>
                        <input type="number" name="MaxMemory" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="CpuSocket">CPU socket:</label>
                        <input type="text" name="CpuSocket" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="GpuSocket">GPU socket:</label>
                        <input type="text" name="GpuSocket" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="MemoryConnection">Memory connection:</label>
                         <input type="text" name="MemoryConnection" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="SizeStandard">Size standard:</label>
                         <input type="text" name="SizeStandard" class="form-control" />
                    </div>
                    `;
            }

            if (type === "Hard disk") {
                fieldsContainer.innerHTML += 
                    `<div class="form-group">
                        <label for="DiskType">Type:</label>
                        <input type="text" name="DiskType" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="Capacity">Capacity:</label>
                        <input type="text" name="Capacity" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="ReadingSpeed">Reading speed:</label>
                        <input type="number" name="ReadingSpeed" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="WritingSpeed">Writing speed:</label>
                        <input type="text" name="WritingSpeed" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="Connection">Connection:</label>
                        <input type="text" name="Connection" class="form-control" />
                    </div>
                    `;
            }
        }
    </script>
}

KompiuteriuSurinkimoSistema-master/KompiuteriuSurinkimoSistema-master/KompiuteriuSurinkimoSistema/Views/Part/PartInfo.cshtml
@model ComputerBuildSystem.Models.ComputerPart

@{
    ViewData["Title"] = "Part Information";
}

<h2>@ViewData["Title"]</h2>


<div class="card">
    <div class="card-body">
        <h3 class="card-title">@Model.Name</h3>
        <h4 class="card-subtitle mb-2 text-muted">@Model.Type</h4>
        <p class="card-text">Manufacturer: @Model.Manufacturer</p>
        <p>Model: @Model.Model</p>
        <p>Price: @Model.Price.ToString("C2")</p>
        <p>Quantity: @Model.Quantity</p>
        <p>Description: @Model.Description</p>
        @if (Model.Benchmark != null)
        {
                <p>Benchmark: @Model.Benchmark</p>
        }

        @switch (Model.Type)
        {
            case "CPU":
                        <p>Memory: @Model.Cpu.Memory</p>
                        <p>Connection: @Model.Cpu.Connection</p>
                        <p>Cores: @Model.Cpu.Cores</p>
                        <p>Frequency: @Model.Cpu.Frequency</p>
                        <p>Power: @Model.Cpu.Power</p>
                break;
            case "GPU":
                        <p>Memory: @Model.Gpu.Memory</p>
                        <p>Memory Type: @Model.Gpu.MemoryType</p>
                        <p>Memory Frequency: @Model.Gpu.MemoryFrequency</p>
                        <p>Connection: @Model.Gpu.Connection</p>
                        <p>RAM Quantity: @Model.Gpu.RamQuantity</p>
                        <p>RAM Type: @Model.Gpu.RamType</p>
                        <p>Power: @Model.Gpu.Power</p>
                break;
            case "RAM":
                        <p>Type: @Model.Ram.Type</p>
                        <p>Frequency: @Model.Ram.Frequency</p>
                        <p>Voltage: @Model.Ram.Voltage</p>
                break;
            case "Motherboard":
                        <p>Maximum Memory Frequency: @Model.Motherboard.MaximumMemoryFrequency</p>
                        <p>Memory Standard: @Model.Motherboard.MemoryStandart</p>
                        <p>Maximum Memory Amount: @Model.Motherboard.MaximumAmountOfMemory</p>
                        <p>CPU Socket: @Model.Motherboard.CpuSocket</p>
                        <p>GPU Socket: @Model.Motherboard.GpuSocket</p>
                        <p>Memory Connection: @Model.Motherboard.MemoryConnection</p>
                break;
            case "PSU":
                        <p>Power: @Model.Psu.Power</p>
                        <p>Size Standard: @Model.Psu.SizeStandart</p>
                break;
            case "Case":
                        <p>Standards: @Model.Case.Standarts</p>
                        <p>Dimensions: @Model.Case.Dimensions</p>
                        <p>Color: @Model.Case.Color</p>
                break;
            case "Hard disk":
                        <p>Type: @Model.HardDisk.Type</p>
                        <p>Capacity: @Model.HardDisk.Capacity</p>
                        <p>Reading Speed: @Model.HardDisk.ReadingSpeed</p>
                        <p>Writing Speed: @Model.HardDisk.WritingSpeed</p>
                        <p>Connection: @Model.HardDisk.Connection</p>
                break;
        }
    </div>
</div>

KompiuteriuSurinkimoSistema-master/KompiuteriuSurinkimoSistema-master/KompiuteriuSurinkimoSistema/Views/Part/PartList.cshtml
@model IEnumerable<ComputerPart>

@{
    ViewData["Title"] = "Part List";
}

<h2>@ViewData["Title"]</h2>

<div style="text-align:right; margin-bottom: 10px;">
    <a asp-action="OpenAddPart" class="btn btn-success">Add part</a>
</div>

<form asp-action="Filter" method="get">
    <div class="form-group">
        <label for="type">Filter by Type:</label>
        <select name="type" class="form-control">
            <option value="">All</option>
            <option value="Case">Cases</option>
            <option value="PSU">PSUs</option>
            <option value="Hard disk">Hard disks</option>
            <option value="GPU">GPUs</option>
            <option value="CPU">CPUs</option>
            <option value="RAM">RAM</option>
            <option value="Motherboard">Motherboards</option>
        </select>
        <input type="hidden" name="parts" value=@Model>
    </div>
    <button type="submit" class="btn btn-primary" style="margin: 5px;">Filter</button>
</form>


<div class="container-fluid">
    <div class="row">
        <div class="col-md-9 d-flex flex-row flex-wrap overflow-auto">
            @foreach (var part in Model)
            {
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">@part.Name</h5>
                            <h6 class="card-subtitle mb-2 text-muted">@part.Manufacturer - @part.Model</h6>
                            <p class="card-text">
                                <strong>Type:</strong> @part.Type <br>
                                <strong>Price:</strong> @part.Price.ToString("C2") <br>
                                <strong>Quantity:</strong> @part.Quantity <br>
                                <strong>Description:</strong> @part.Description
                            </p>
                            <a asp-action="OpenPartInfo" asp-route-id="@part.Id" class="btn btn-info">Part info</a>
                            <a asp-action="OpenEditPart" asp-route-id="@part.Id" class="btn btn-primary">Edit</a>
                            <button onclick="DeletePart('@part.Id', '@part.Name');" class="btn btn-danger">Delete Part</button>
                            @if (part.Type == "GPU")
                            {
                                <a asp-action="GPUCompare" asp-route-id="@part.Id" class="btn btn-primary">Compare</a>
                            }
                            <a asp-action="AddToCart" asp-route-id="@part.Id" class="btn btn-info flex-fill ml-4">Add to Cart</a>
                        </div>
                    </div>
                </div>
            }
        </div>


        <div class="col-md-3">
            <h3>GPU comparison</h3>
            @if (ViewBag.CompareGPU != null && ViewBag.CompareGPU.Count > 0)
            {
                double sum = 0;
                foreach (var part in ViewBag.CompareGPU)
                {
                    sum += (part as ComputerPart).Price;
                    <div class="card mb-2">
                        <div class="card-body">
                            <h5 class="card-title">@part.Name</h5>
                            <p class="card-text">
                                <strong>Type:</strong> @part.Type <br>
                                @part.Price €
                            </p>
                        </div>
                    </div>
                }

                <div class="d-flex justify-content-between mt-2 px-3 py-1">
                    <a asp-action="OpenGPU" class="btn btn-primary">Compare GPU</a>
                </div>
            }
            else
            {
                <p>No GPUs selected.</p>
            }
        </div>
    </div>
</div>


<script>
    function DeletePart(id) {
        fetch('@Url.Action("DeletePart", "Part")' + '?id=' + id)
            .then(response => response.json())
            .then(data => {
                if (!data.confirm) {
                    alert(data.message);
                } else {
                    if (confirm(data.message)) {
                        window.location.href = '@Url.Action("Delete", "Part")' + '?id=' + id;
                    }
                }
            });
    }
</script>